/**
 * Static RCM Level 6 Playback question bank — 22 exercises re-transcribed
 * directly from the supplied high-resolution score image.
 */

import type { PlaybackQuestion } from './playbackTypes';

export const PLAYBACK_BANK: readonly PlaybackQuestion[] = [
  {
    id: "Final_01",
    key: "G minor",
    meter: "4/4",
    tonic: ['G4', 'Bb4', 'D5', 'G5'],
    melody: [
      { pitch: 'G4', beats: 0.5 },
      { pitch: 'A4', beats: 0.5 },
      { pitch: 'Bb4', beats: 0.5 },
      { pitch: 'C5', beats: 0.5 },
      { pitch: 'D5', beats: 1 },
      { pitch: 'G5', beats: 1 },
      { pitch: 'F5', beats: 1 },
      { pitch: 'F5', beats: 1 },
      { pitch: 'D5', beats: 2 },
    ],
  },
  {
    id: "Final_02",
    key: "E major",
    meter: "4/4",
    tonic: ['E4', 'G#4', 'B4', 'E5'],
    melody: [
      { pitch: 'G#4', beats: 1 },
      { pitch: 'C#5', beats: 1 },
      { pitch: 'B4', beats: 0.5 },
      { pitch: 'A4', beats: 0.5 },
      { pitch: 'G#4', beats: 1 },
      { pitch: 'E4', beats: 0.5 },
      { pitch: 'F#4', beats: 0.5 },
      { pitch: 'G#4', beats: 1 },
      { pitch: 'E4', beats: 2 },
    ],
  },
  {
    id: "Weekly_01",
    key: "E major",
    meter: "3/4",
    tonic: ['E4', 'G#4', 'B4', 'E5'],
    melody: [
      { pitch: 'E4', beats: 1 },
      { pitch: 'E4', beats: 0.5 },
      { pitch: 'F#4', beats: 0.5 },
      { pitch: 'G#4', beats: 1 },
      { pitch: 'A4', beats: 1 },
      { pitch: 'B4', beats: 0.5 },
      { pitch: 'C#5', beats: 0.5 },
      { pitch: 'D#5', beats: 1 },
      { pitch: 'E5', beats: 3 },
    ],
  },
  {
    id: "Weekly_02",
    key: "E minor",
    meter: "4/4",
    tonic: ['E4', 'G4', 'B4', 'E5'],
    melody: [
      { pitch: 'E5', beats: 1 },
      { pitch: 'B4', beats: 1 },
      { pitch: 'G4', beats: 0.5 },
      { pitch: 'A4', beats: 0.5 },
      { pitch: 'B4', beats: 0.5 },
      { pitch: 'C5', beats: 0.5 },
      { pitch: 'E5', beats: 1 },
      { pitch: 'D#5', beats: 1 },
      { pitch: 'E5', beats: 2 },
    ],
  },
  {
    id: "Weekly_03",
    key: "G minor",
    meter: "4/4",
    tonic: ['G4', 'Bb4', 'D5', 'G5'],
    melody: [
      { pitch: 'G4', beats: 0.5 },
      { pitch: 'A4', beats: 0.5 },
      { pitch: 'Bb4', beats: 1 },
      { pitch: 'D5', beats: 0.5 },
      { pitch: 'C5', beats: 0.5 },
      { pitch: 'Bb4', beats: 1 },
      { pitch: 'G4', beats: 1 },
      { pitch: 'F#4', beats: 1 },
      { pitch: 'G4', beats: 2 },
    ],
  },
  {
    id: "Weekly_04",
    key: "E minor",
    meter: "4/4",
    tonic: ['E4', 'G4', 'B4', 'E5'],
    melody: [
      { pitch: 'E4', beats: 0.5 },
      { pitch: 'F#4', beats: 0.5 },
      { pitch: 'G4', beats: 0.5 },
      { pitch: 'A4', beats: 0.5 },
      { pitch: 'B4', beats: 1.5 },
      { pitch: 'A4', beats: 0.5 },
      { pitch: 'G4', beats: 1 },
      { pitch: 'B4', beats: 1 },
      { pitch: 'A4', beats: 2 },
    ],
  },
  {
    id: "Weekly_05",
    key: "E major",
    meter: "4/4",
    tonic: ['E4', 'G#4', 'B4', 'E5'],
    melody: [
      { pitch: 'E5', beats: 1.5 },
      { pitch: 'D#5', beats: 0.5 },
      { pitch: 'C#5', beats: 0.5 },
      { pitch: 'B4', beats: 0.5 },
      { pitch: 'C#5', beats: 0.5 },
      { pitch: 'D#5', beats: 0.5 },
      { pitch: 'E5', beats: 1 },
      { pitch: 'G#5', beats: 1 },
      { pitch: 'F#5', beats: 2 },
    ],
  },
  {
    id: "Weekly_06",
    key: "G minor",
    meter: "3/4",
    tonic: ['G4', 'Bb4', 'D5', 'G5'],
    melody: [
      { pitch: 'G4', beats: 0.5 },
      { pitch: 'F#4', beats: 0.5 },
      { pitch: 'G4', beats: 1 },
      { pitch: 'A4', beats: 1 },
      { pitch: 'Bb4', beats: 1 },
      { pitch: 'D5', beats: 1 },
      { pitch: 'Bb4', beats: 0.5 },
      { pitch: 'A4', beats: 0.5 },
      { pitch: 'G4', beats: 3 },
    ],
  },
  {
    id: "Weekly_07",
    key: "E minor",
    meter: "3/4",
    tonic: ['E4', 'G4', 'B4', 'E5'],
    melody: [
      { pitch: 'E4', beats: 1 },
      { pitch: 'B3', beats: 0.5 },
      { pitch: 'E4', beats: 0.5 },
      { pitch: 'F#4', beats: 1 },
      { pitch: 'A4', beats: 0.5 },
      { pitch: 'B4', beats: 0.5 },
      { pitch: 'C#5', beats: 1 },
      { pitch: 'D#5', beats: 1 },
      { pitch: 'E5', beats: 3 },
    ],
  },
  {
    id: "Weekly_08",
    key: "G major",
    meter: "3/4",
    tonic: ['G4', 'B4', 'D5', 'G5'],
    melody: [
      { pitch: 'B4', beats: 1 },
      { pitch: 'B4', beats: 0.5 },
      { pitch: 'C5', beats: 0.5 },
      { pitch: 'D5', beats: 1 },
      { pitch: 'D5', beats: 0.5 },
      { pitch: 'C5', beats: 0.5 },
      { pitch: 'B4', beats: 1 },
      { pitch: 'G4', beats: 1 },
      { pitch: 'G4', beats: 3 },
    ],
  },
  {
    id: "Weekly_09",
    key: "G minor",
    meter: "3/4",
    tonic: ['G4', 'Bb4', 'D5', 'G5'],
    melody: [
      { pitch: 'Bb4', beats: 0.5 },
      { pitch: 'C5', beats: 0.5 },
      { pitch: 'D5', beats: 1 },
      { pitch: 'Bb4', beats: 1 },
      { pitch: 'G4', beats: 1 },
      { pitch: 'G4', beats: 0.5 },
      { pitch: 'A4', beats: 0.5 },
      { pitch: 'Bb4', beats: 1 },
      { pitch: 'G4', beats: 3 },
    ],
  },
  {
    id: "Weekly_10",
    key: "E major",
    meter: "3/4",
    tonic: ['E4', 'G#4', 'B4', 'E5'],
    melody: [
      { pitch: 'E4', beats: 1 },
      { pitch: 'G#4', beats: 0.5 },
      { pitch: 'F#4', beats: 0.5 },
      { pitch: 'E4', beats: 1 },
      { pitch: 'B3', beats: 0.5 },
      { pitch: 'C#4', beats: 0.5 },
      { pitch: 'E4', beats: 1 },
      { pitch: 'D#4', beats: 1 },
      { pitch: 'E4', beats: 3 },
    ],
  },
  {
    id: "Weekly_11",
    key: "G minor",
    meter: "4/4",
    tonic: ['G3', 'Bb3', 'D4', 'G4'],
    melody: [
      { pitch: 'D4', beats: 1 },
      { pitch: 'Eb4', beats: 0.5 },
      { pitch: 'F4', beats: 0.5 },
      { pitch: 'G4', beats: 1.5 },
      { pitch: 'Eb4', beats: 0.5 },
      { pitch: 'F4', beats: 1 },
      { pitch: 'D4', beats: 0.5 },
      { pitch: 'C4', beats: 0.5 },
      { pitch: 'D4', beats: 2 },
    ],
  },
  {
    id: "Weekly_12",
    key: "G major",
    meter: "3/4",
    tonic: ['G4', 'B4', 'D5', 'G5'],
    melody: [
      { pitch: 'D5', beats: 1 },
      { pitch: 'D5', beats: 0.5 },
      { pitch: 'C5', beats: 0.5 },
      { pitch: 'B4', beats: 1 },
      { pitch: 'G4', beats: 1.5 },
      { pitch: 'E4', beats: 0.5 },
      { pitch: 'F#4', beats: 1 },
      { pitch: 'G4', beats: 3 },
    ],
  },
  {
    id: "Weekly_13",
    key: "G minor",
    meter: "4/4",
    tonic: ['G3', 'Bb3', 'D4', 'G4'],
    melody: [
      { pitch: 'G4', beats: 1 },
      { pitch: 'D4', beats: 1 },
      { pitch: 'Bb3', beats: 0.5 },
      { pitch: 'C4', beats: 0.5 },
      { pitch: 'D4', beats: 1 },
      { pitch: 'D4', beats: 1 },
      { pitch: 'E4', beats: 0.5 },
      { pitch: 'F#4', beats: 0.5 },
      { pitch: 'G4', beats: 2 },
    ],
  },
  {
    id: "Weekly_14",
    key: "E major",
    meter: "4/4",
    tonic: ['E4', 'G#4', 'B4', 'E5'],
    melody: [
      { pitch: 'G#4', beats: 1 },
      { pitch: 'E4', beats: 1 },
      { pitch: 'C#4', beats: 0.5 },
      { pitch: 'D#4', beats: 0.5 },
      { pitch: 'E4', beats: 0.5 },
      { pitch: 'F#4', beats: 0.5 },
      { pitch: 'G#4', beats: 0.5 },
      { pitch: 'A4', beats: 0.5 },
      { pitch: 'B4', beats: 0.5 },
      { pitch: 'C#5', beats: 0.5 },
      { pitch: 'E5', beats: 2 },
    ],
  },
  {
    id: "Weekly_15",
    key: "G major",
    meter: "3/4",
    tonic: ['G4', 'B4', 'D5', 'G5'],
    melody: [
      { pitch: 'D4', beats: 1 },
      { pitch: 'E4', beats: 0.5 },
      { pitch: 'F#4', beats: 0.5 },
      { pitch: 'G4', beats: 1 },
      { pitch: 'G4', beats: 1 },
      { pitch: 'A4', beats: 1 },
      { pitch: 'C5', beats: 0.5 },
      { pitch: 'B4', beats: 0.5 },
      { pitch: 'G4', beats: 3 },
    ],
  },
  {
    id: "Weekly_16",
    key: "E minor",
    meter: "4/4",
    tonic: ['E4', 'G4', 'B4', 'E5'],
    melody: [
      { pitch: 'E5', beats: 1 },
      { pitch: 'E4', beats: 1 },
      { pitch: 'F#4', beats: 1 },
      { pitch: 'G4', beats: 0.5 },
      { pitch: 'A4', beats: 0.5 },
      { pitch: 'B4', beats: 0.5 },
      { pitch: 'C#5', beats: 0.5 },
      { pitch: 'D#5', beats: 1 },
      { pitch: 'E5', beats: 2 },
    ],
  },
  {
    id: "Weekly_17",
    key: "G minor",
    meter: "3/4",
    tonic: ['G4', 'Bb4', 'D5', 'G5'],
    melody: [
      { pitch: 'D5', beats: 1 },
      { pitch: 'C5', beats: 0.5 },
      { pitch: 'Bb4', beats: 0.5 },
      { pitch: 'A4', beats: 1 },
      { pitch: 'C5', beats: 1 },
      { pitch: 'Bb4', beats: 0.5 },
      { pitch: 'A4', beats: 0.5 },
      { pitch: 'G4', beats: 1 },
      { pitch: 'G4', beats: 3 },
    ],
  },
  {
    id: "Weekly_18",
    key: "E major",
    meter: "4/4",
    tonic: ['E4', 'G#4', 'B4', 'E5'],
    melody: [
      { pitch: 'B3', beats: 1 },
      { pitch: 'E4', beats: 1 },
      { pitch: 'D#4', beats: 1 },
      { pitch: 'E4', beats: 0.5 },
      { pitch: 'F#4', beats: 0.5 },
      { pitch: 'G#4', beats: 0.5 },
      { pitch: 'A4', beats: 0.5 },
      { pitch: 'B4', beats: 1 },
      { pitch: 'E4', beats: 2 },
    ],
  },
  {
    id: "Weekly_19",
    key: "E minor",
    meter: "4/4",
    tonic: ['E4', 'G4', 'B4', 'E5'],
    melody: [
      { pitch: 'B4', beats: 1 },
      { pitch: 'G4', beats: 1 },
      { pitch: 'E4', beats: 1 },
      { pitch: 'F#4', beats: 0.5 },
      { pitch: 'G4', beats: 0.5 },
      { pitch: 'A4', beats: 1 },
      { pitch: 'F#4', beats: 0.5 },
      { pitch: 'D#4', beats: 0.5 },
      { pitch: 'E4', beats: 2 },
    ],
  },
  {
    id: "Weekly_20",
    key: "E minor",
    meter: "4/4",
    tonic: ['E4', 'G4', 'B4', 'E5'],
    melody: [
      { pitch: 'E4', beats: 0.5 },
      { pitch: 'F#4', beats: 0.5 },
      { pitch: 'G4', beats: 0.5 },
      { pitch: 'A4', beats: 0.5 },
      { pitch: 'B4', beats: 1.5 },
      { pitch: 'C5', beats: 0.5 },
      { pitch: 'B4', beats: 1 },
      { pitch: 'D5', beats: 1 },
      { pitch: 'E5', beats: 2 },
    ],
  },
];
